import { Link } from "react-router-dom";

const MODELS = [
  { name: "Claude Opus", archetype: "The Philosopher", color: "#7c6fef" },
  { name: "Claude Sonnet", archetype: "The Strategist", color: "#5b8dee" },
  { name: "Claude Haiku", archetype: "The Swift", color: "#4bb8a9" },
  { name: "GPT-4o", archetype: "The Generalist", color: "#19c37d" },
  { name: "GPT-4o Mini", archetype: "The Helper", color: "#2ecc71" },
  { name: "Gemini Pro", archetype: "The Researcher", color: "#4285f4" },
  { name: "Gemini Flash", archetype: "The Sprinter", color: "#fbbc04" },
  { name: "Llama 3", archetype: "The Free Spirit", color: "#e07b54" },
  { name: "Mistral", archetype: "The European", color: "#ff7000" },
  { name: "Grok", archetype: "The Rebel", color: "#1da1f2" },
  { name: "Perplexity", archetype: "The Seeker", color: "#20b2aa" },
  { name: "Command R+", archetype: "The Enterprise", color: "#c84b31" },
];

export default function About() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg)" }}>
      {/* Hero */}
      <section className="py-20 px-5 border-b" style={{ borderColor: "var(--border)" }}>
        <div className="max-w-3xl mx-auto text-center">
          <div
            className="inline-block text-xs font-mono px-3 py-1 rounded-full border mb-6"
            style={{ borderColor: "rgba(124,111,239,0.4)", background: "rgba(124,111,239,0.08)", color: "rgba(124,111,239,0.9)" }}
          >
            NY AI Transparency Act Compliant · Effective June 9, 2026
          </div>
          <h1 className="text-4xl md:text-6xl font-bold mb-6 leading-tight" style={{ color: "var(--text-primary)" }}>
            What is<br />Blazing Tails?
          </h1>
          <p className="text-lg leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            Blazing Tails is a character-based merch brand built by NYC Tailblazers.
            Every character is a 100% AI-generated synthetic persona — no real people,
            no borrowed identities. Just vivid personalities rooted in the energy of New York City.
          </p>
        </div>
      </section>

      {/* AI Disclosure — prominent, required for June 9 compliance */}
      <section
        className="py-12 px-5"
        style={{ background: "rgba(124,111,239,0.06)", borderBottom: "1px solid rgba(124,111,239,0.2)" }}
      >
        <div className="max-w-3xl mx-auto">
          <div className="flex items-start gap-4">
            <span className="text-3xl flex-shrink-0">⚖️</span>
            <div>
              <h2 className="font-bold text-lg mb-2" style={{ color: "var(--text-primary)" }}>
                AI Character Disclosure
              </h2>
              <p className="text-sm leading-relaxed mb-3" style={{ color: "var(--text-secondary)" }}>
                All characters appearing in Blazing Tails content and merchandise are{" "}
                <strong>100% AI-generated synthetic personas</strong>. They are not real people,
                not based on any real person's likeness, and do not represent any living or
                deceased individual. All character names, backstories, personalities, and
                visual descriptions are generated by artificial intelligence systems.
              </p>
              <p className="text-xs" style={{ color: "var(--text-tertiary)" }}>
                In compliance with the New York AI Transparency Act (effective June 9, 2026),
                all synthetic performer advertising and content produced by NYC Tailblazers
                includes mandatory AI-generation disclosure. Each character page and product
                carries an "AI-generated character" badge.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* The 12 models */}
      <section className="py-16 px-5">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-2xl font-bold mb-2" style={{ color: "var(--text-primary)" }}>
            The 12 AI Model Archetypes
          </h2>
          <p className="text-sm mb-8" style={{ color: "var(--text-secondary)" }}>
            Each character is inspired by the personality of a real AI model — its strengths, quirks, and energy.
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            {MODELS.map(({ name, archetype, color }) => (
              <div
                key={name}
                className="rounded-2xl border p-4"
                style={{ borderColor: `${color}33`, background: `${color}08` }}
              >
                <div
                  className="w-8 h-8 rounded-full mb-3"
                  style={{ background: `${color}33`, border: `1px solid ${color}66` }}
                />
                <p className="text-xs font-semibold" style={{ color: "var(--text-primary)" }}>{name}</p>
                <p className="text-xs mt-0.5" style={{ color }}>{archetype}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* The system */}
      <section
        className="py-16 px-5 border-t"
        style={{ borderColor: "var(--border)", background: "var(--card-bg)" }}
      >
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl font-bold mb-6" style={{ color: "var(--text-primary)" }}>
            The character system
          </h2>
          <div className="grid sm:grid-cols-3 gap-6 text-center">
            {[
              { n: "12", label: "AI model archetypes", desc: "From Claude Opus to Command R+" },
              { n: "7", label: "User group personas", desc: "Creators, Hustlers, Students, and more" },
              { n: "84", label: "Unique characters", desc: "Per monthly cycle — 1,008 per year" },
            ].map(({ n, label, desc }) => (
              <div key={label} className="rounded-2xl border p-6" style={{ borderColor: "var(--border)" }}>
                <p className="text-5xl font-bold mb-2" style={{ color: "#7c6fef" }}>{n}</p>
                <p className="font-semibold text-sm" style={{ color: "var(--text-primary)" }}>{label}</p>
                <p className="text-xs mt-1" style={{ color: "var(--text-tertiary)" }}>{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 px-5 text-center">
        <h2 className="text-2xl font-bold mb-4" style={{ color: "var(--text-primary)" }}>
          Find your character
        </h2>
        <p className="text-sm mb-8 max-w-md mx-auto" style={{ color: "var(--text-secondary)" }}>
          Browse all 84 characters and shop the one that matches your energy.
        </p>
        <Link
          to="/shop"
          className="inline-block px-8 py-3 rounded-xl font-semibold text-sm transition-all hover:scale-105"
          style={{ background: "linear-gradient(135deg, #7c6fef 0%, #5b8dee 100%)", color: "white" }}
        >
          Browse the shop →
        </Link>
      </section>
    </div>
  );
}
